add_executable(Task1 common.h common.cpp task1.cpp)
target_include_directories(Task1 PUBLIC ../LibraryCPPClass)
target_link_libraries(Task1 LibraryCPPClass)

add_executable(Task2 common.h common.cpp task2.cpp)
target_include_directories(Task2 PUBLIC ../LibraryCPPClass)
target_link_libraries(Task2 LibraryCPPClass)

add_test(NAME Task1_01 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_1.txt)
set_property(TEST Task1_01 PROPERTY PASS_REGULAR_EXPRESSION "^\n0\n?$")
add_test(NAME Task1_02 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_2.txt)
set_property(TEST Task1_02 PROPERTY PASS_REGULAR_EXPRESSION "^0 1 2 3 4\n5\n?$")
add_test(NAME Task1_03 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_3.txt)
set_property(TEST Task1_03 PROPERTY PASS_REGULAR_EXPRESSION "^\n0\n?$")
add_test(NAME Task1_04 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_4.txt)
set_property(TEST Task1_04 PROPERTY PASS_REGULAR_EXPRESSION "^\n0\n?$")
add_test(NAME Task1_05 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_5.txt)
set_property(TEST Task1_05 PROPERTY PASS_REGULAR_EXPRESSION "^\n0\n?$")
add_test(NAME Task1_06 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_6.txt)
set_property(TEST Task1_06 PROPERTY PASS_REGULAR_EXPRESSION "^0\n1\n?$")
add_test(NAME Task1_07 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_7.txt)
set_property(TEST Task1_07 PROPERTY PASS_REGULAR_EXPRESSION "^0 2 4 5\n4\n?$")
add_test(NAME Task1_08 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_8.txt)
set_property(TEST Task1_08 PROPERTY PASS_REGULAR_EXPRESSION "^0\n1\n?$")
add_test(NAME Task1_09 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_9.txt)
set_property(TEST Task1_09 PROPERTY PASS_REGULAR_EXPRESSION "^0\n1\n?$")
add_test(NAME Task1_10 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task1_10.txt)
set_property(TEST Task1_10 PROPERTY PASS_REGULAR_EXPRESSION "^0 2 4\n3\n?$")

# ---------- Task2 ----------
add_test(NAME Task2_01 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_1.txt)
set_property(TEST Task2_01 PROPERTY PASS_REGULAR_EXPRESSION "^4 5 0 0 0\n?$")
add_test(NAME Task2_02 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_2.txt)
set_property(TEST Task2_02 PROPERTY PASS_REGULAR_EXPRESSION "^0 0 1 2 3\n?$")
add_test(NAME Task2_03 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_3.txt)
set_property(TEST Task2_03 PROPERTY PASS_REGULAR_EXPRESSION "^1 2 3 4 5\n?$")
add_test(NAME Task2_04 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_4.txt)
set_property(TEST Task2_04 PROPERTY PASS_REGULAR_EXPRESSION "^0 0 0 0\n?$")
add_test(NAME Task2_05 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_5.txt)
set_property(TEST Task2_05 PROPERTY PASS_REGULAR_EXPRESSION "^0 0 0\n?$")
add_test(NAME Task2_06 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_6.txt)
set_property(TEST Task2_06 PROPERTY PASS_REGULAR_EXPRESSION "^0\n?$")
add_test(NAME Task2_07 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_7.txt)
set_property(TEST Task2_07 PROPERTY PASS_REGULAR_EXPRESSION "^0 0 0 0 1\n?$")
add_test(NAME Task2_08 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_8.txt)
set_property(TEST Task2_08 PROPERTY PASS_REGULAR_EXPRESSION "^-2 -3 0 4 5 0\n?$")
add_test(NAME Task2_09 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_9.txt)
set_property(TEST Task2_09 PROPERTY PASS_REGULAR_EXPRESSION "^0 10 20 30 40 50\n?$")
add_test(NAME Task2_10 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/task2_10.txt)
set_property(TEST Task2_10 PROPERTY PASS_REGULAR_EXPRESSION "^5 0 0 0 0\n?$")